import dspy
import os
import argparse
from story_modules import (
    QuestionGenerator,
    CorePremiseGenerator,
    SpineTemplateGenerator,
    StoryGenerator
)
from world_bible_modules import WorldBibleGenerator

# A mock LM to avoid needing an API key for automated testing
class MockLM(dspy.LM):
    def __init__(self):
        super().__init__(model="mock")

    def __call__(self, prompt=None, messages=None, **kwargs):
        # The prompt/messages will contain the field to generate, we can fake JSON response since DSPy uses Pydantic
        content = prompt if prompt else str(messages)
        if "questions_with_answers" in content:
            return ['```json\n{"questions_with_answers": [{"question": "Mock?", "proposed_answer": "Yes"}]}\n```']
        # Check what field is requested to be generated by DSPy JSON adapter.
        # Usually it asks to output a specific JSON schema.
        if "questions_with_answers" in content:
            return ['```json\n{"questions_with_answers": [{"question": "Mock?", "proposed_answer": "Yes"}]}\n```']
        # For dspy outputs we can also parse out the name of the expected output type from the system prompt keys list
        if '"questions_with_answers"' in content and "proposed_answer" in content:
            return ['```json\n{"questions_with_answers": [{"question": "Mock?", "proposed_answer": "Yes"}]}\n```']

        # DSPy puts the schema in the prompt, let's extract the key being asked for:
        # e.g., "This JSON object must only contain the following keys: chapter_plan."

        # We can also just look at the last fields being asked for
        if "[[ ## chapter_text ## ]]" in content or ('"chapter_text"' in content and "immersive chapter" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "title": "Mock Title", "chapter_text": "Mock chapter text"}\n```']
        if "[[ ## story ## ]]" in content or ('"story"' in content and "The final generated story" in content):
            return ['```json\n{"story": "Mock final story"}\n```']
        if "[[ ## enhancers_guide ## ]]" in content or ('"enhancers_guide"' in content and "evaluating which story enhancers" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "enhancers_guide": "Mock enhancers guide"}\n```']
        if "[[ ## chapter_plan ## ]]" in content or ('"chapter_plan"' in content and "Each arc broken into chapters" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "chapter_plan": "Mock chapter plan"}\n```']
        if "[[ ## arc_outline ## ]]" in content or ('"arc_outline"' in content and "5-10 major events" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "arc_outline": "Mock arc outline"}\n```']
        if "[[ ## world_bible ## ]]" in content or ('"world_bible"' in content and "setting, lore, and characters" in content):
            return ['```json\n{"world_bible": "Mock world bible"}\n```']
        if "[[ ## plot_timeline ## ]]" in content or ('"plot_timeline"' in content and "A plot timeline." in content):
            return ['```json\n{"reasoning": "Mock reasoning", "plot_timeline": "Mock timeline"}\n```']
        if "[[ ## locations ## ]]" in content or ('"locations"' in content and "Places and locations" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "locations": "Mock locations"}\n```']
        if "[[ ## characters ## ]]" in content or ('"characters"' in content and "Character descriptions" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "characters": "Mock characters"}\n```']
        if "[[ ## world_rules ## ]]" in content or ('"world_rules"' in content and "Rules of the world" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "world_rules": "Mock rules"}\n```']
        if "[[ ## spine_template ## ]]" in content or ('"spine_template"' in content and "Once upon a time" in content):
            return ['```json\n{"spine_template": "Mock spine"}\n```']
        if "[[ ## core_premise ## ]]" in content or ('"core_premise"' in content and "summarizing the foundation" in content):
            return ['```json\n{"core_premise": "Mock premise"}\n```']

        # Fallback to general input presence checks but very carefully
        if "questions_with_answers" in content:
            return ['```json\n{"questions_with_answers": [{"question": "Mock?", "proposed_answer": "Yes"}]}\n```']
        elif "core_premise" in content and "spine_template" not in content:
            return ['```json\n{"core_premise": "Mock premise"}\n```']
        elif "spine_template" in content and "world_bible" not in content:
            return ['```json\n{"spine_template": "Mock spine"}\n```']
        elif "world_bible" in content and "arc_outline" not in content:
            return ['```json\n{"world_bible": "Mock world bible"}\n```']
        elif "arc_outline" in content and "chapter_plan" not in content:
            return ['```json\n{"arc_outline": "Mock arc outline"}\n```']
        elif "chapter_plan" in content and "enhancers_guide" not in content and "story" not in content:
            return ['```json\n{"chapter_plan": "Mock chapter plan"}\n```']
        elif "enhancers_guide" in content and "story" not in content and "chapter_text" not in content:
            return ['```json\n{"enhancers_guide": "Mock enhancers guide"}\n```']
        elif "chapter_text" in content:
            return ['```json\n{"reasoning": "Mock reasoning", "title": "Mock Title", "chapter_text": "Mock chapter text"}\n```']
        elif "story" in content:
            return ['```json\n{"story": "Mock final story"}\n```']
        return ["Mock response"]

def test_pipeline(model_name="ollama_chat/llama3", api_base="http://localhost:11434", api_key=None):
    kwargs = {"max_tokens": 2000}
    if api_base:
        kwargs["api_base"] = api_base

    if api_key is not None:
        kwargs["api_key"] = api_key
    elif "openai" in model_name.lower():
        env_key = os.environ.get("OPENAI_API_KEY")
        if env_key:
            kwargs["api_key"] = env_key
    elif "ollama" in model_name.lower():
        pass

    print(f"Testing pipeline with model: {model_name}...")

    # For testing in an environment where no actual LLM API is reachable, use the MockLM.
    # To run actual integration tests, you'd provide an active OPENAI_API_KEY or local Ollama running.
    # If the user requested the mock model, or if we want to ensure tests always pass in CI, use MockLM.
    if model_name == "mock" or model_name == "test_mock":
        lm = MockLM()
        dspy.configure(lm=lm)
    else:
        # We assume OPENAI_API_KEY is available in the run_in_bash_session, if not, we skip the actual test
        if "openai" in model_name.lower() and not kwargs.get("api_key"):
            print("OPENAI_API_KEY not found. Skipping full integration test to avoid errors.")
            return

        lm = dspy.LM(model_name, **kwargs)
        dspy.configure(lm=lm)

    idea = "An unnamed child is raised by the Church as the ultimate weapon against demons. As child grows he learns that the church itself is corrupt and breeds demons for controlled chaos. The church recieves funding for protection and as such decides who should recieve help. The child eventually becomes overpowered and turns back on the Church"

    # 1. Questions
    q_gen = QuestionGenerator()
    q_result = q_gen(idea=idea)
    print(f"Generated {len(q_result.questions_with_answers)} questions.")

    # Fake answers
    qa_text = ""
    for q in q_result.questions_with_answers:
        qa_text += f"Q: {q.question}\nA: {q.proposed_answer}\n\n"

    # 2. Core Premise
    cp_gen = CorePremiseGenerator()
    cp_result = cp_gen(idea=idea, qa_pairs=qa_text)
    print("Core Premise generated.")

    # 3. Spine Template
    st_gen = SpineTemplateGenerator()
    st_result = st_gen(core_premise=cp_result.core_premise)
    print("Spine Template generated.")

    # 4. World Bible
    wb_gen = WorldBibleGenerator()
    wb_result = wb_gen(core_premise=cp_result.core_premise, spine_template=st_result.spine_template)
    print("World Bible generated.")

    # 5. Story
    story_gen = StoryGenerator()
    story_result = story_gen(core_premise=cp_result.core_premise, spine_template=st_result.spine_template, world_bible=wb_result.world_bible)
    print("Story generated.")
    print("Test passed successfully!")

    output_filename = "story_output.md"
    print(f"Saving story output to {output_filename}...")
    with open(output_filename, "w", encoding="utf-8") as f:
        f.write("# Story Output\n\n")
        f.write("## Core Premise\n")
        f.write(f"{cp_result.core_premise}\n\n")
        f.write("## Spine Template\n")
        f.write(f"{st_result.spine_template}\n\n")
        f.write("## World Bible\n")
        f.write(f"{wb_result.world_bible}\n\n")
        f.write("## Arc Outline\n")
        f.write(f"{story_result.arc_outline}\n\n")
        f.write("## Chapter Plan\n")
        f.write(f"{story_result.chapter_plan}\n\n")
        f.write("## Enhancers Guide\n")
        f.write(f"{story_result.enhancers_guide}\n\n")
        f.write("## Final Story\n")
        f.write(f"{story_result.story}\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Test AI DSPy Story Writer")
    parser.add_argument("--model", type=str, default=os.environ.get("MODEL", "mock"), help="The language model to use (e.g., openai/gpt-4o-mini, ollama_chat/llama3). Defaults to MODEL env var or mock.")
    parser.add_argument("--llm-url", type=str, default=os.environ.get("LLM_URL", "http://localhost:11434"), help="The custom API base URL (e.g., http://localhost:11434 for Ollama). Defaults to LLM_URL env var or http://localhost:11434.")
    parser.add_argument("--api-key", type=str, default=os.environ.get("API_KEY"), help="The API key for the model. Defaults to API_KEY env var.")

    args = parser.parse_args()

    test_pipeline(model_name=args.model, api_base=args.llm_url, api_key=args.api_key)
