import dspy
import os
import argparse
import logging
import coloredlogs
import pytest
from dotenv import load_dotenv
from unittest.mock import patch, MagicMock
from story_modules import (
    QuestionGenerator,
    QuestionWithAnswer,
    CharacterVisual,
    CorePremiseGenerator,
    SpineTemplateGenerator,
    StoryGenerator,
    ChapterInpaintingGenerator,
    CharacterVisualDescriber,
    SceneImagePromptGenerator,
)
from world_bible_modules import WorldBibleGenerator
from main import initialize_text_generators

load_dotenv()

# A mock LM to avoid needing an API key for automated testing
class MockLM(dspy.LM):
    def __init__(self):
        super().__init__(model="mock")

    def __call__(self, prompt=None, messages=None, **kwargs):
        # The prompt/messages will contain the field to generate, we can fake JSON response since DSPy uses Pydantic
        content = prompt if prompt else str(messages)
        if "questions_with_answers" in content:
            return ['```json\n{"questions_with_answers": [{"question": "Mock?", "proposed_answer": "Yes"}]}\n```']
        # Check what field is requested to be generated by DSPy JSON adapter.
        # Usually it asks to output a specific JSON schema.
        if "questions_with_answers" in content:
            return ['```json\n{"questions_with_answers": [{"question": "Mock?", "proposed_answer": "Yes"}]}\n```']
        # For dspy outputs we can also parse out the name of the expected output type from the system prompt keys list
        if '"questions_with_answers"' in content and "proposed_answer" in content:
            return ['```json\n{"questions_with_answers": [{"question": "Mock?", "proposed_answer": "Yes"}]}\n```']

        # DSPy puts the schema in the prompt, let's extract the key being asked for:
        # e.g., "This JSON object must only contain the following keys: chapter_plan."

        # We can also just look at the last fields being asked for
        if "[[ ## character_visuals ## ]]" in content or ('"character_visuals"' in content and "reference_mix" in content):
            return ['```json\n{"character_visuals": [{"name": "Mock Hero", "reference_mix": "a mix of Guts from Berserk and Zuko from Avatar", "distinguishing_features": "short black hair, amber eyes, burn scar on left cheek, dark leather armor", "full_prompt": "anime portrait, a mix of Guts from Berserk and Zuko from Avatar, short black hair, amber eyes, burn scar on left cheek, dark leather armor"}]}\n```']
        if "[[ ## image_prompt ## ]]" in content or ('"image_prompt"' in content and "anime scene" in content):
            return ['```json\n{"image_prompt": "anime scene, a warrior with short black hair and amber eyes standing in a dark cathedral, dramatic lighting"}\n```']
        if "[[ ## random_detail ## ]]" in content or ('"random_detail"' in content and "naturally woven" in content):
            return ['```json\n{"random_detail": "A small paper unicorn sat perched on the corner of the desk, its horn casting a faint shadow in the candlelight."}\n```']
        if (
            "[[ ## chapter_text ## ]]" in content
            or ('"chapter_text"' in content and "immersive chapter" in content)
        ) and '"expanded_chapter_text"' not in content:
            return ['```json\n{"reasoning": "Mock reasoning", "title": "Mock Title", "chapter_text": "Mock chapter text"}\n```']
        if "[[ ## expanded_chapter_text ## ]]" in content or '"expanded_chapter_text"' in content:
            return ['```json\n{"reasoning": "Mock reasoning", "expanded_chapter_text": "Mock expanded chapter text with richer detail and slower pacing."}\n```']
        if "[[ ## story ## ]]" in content or ('"story"' in content and "The final generated story" in content):
            return ['```json\n{"story": "Mock final story"}\n```']
        if "[[ ## enhancers_guide ## ]]" in content or ('"enhancers_guide"' in content and "evaluating which story enhancers" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "enhancers_guide": "Mock enhancers guide"}\n```']
        if "[[ ## chapter_plan ## ]]" in content or ('"chapter_plan"' in content and "Each arc broken into chapters" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "chapter_plan": ["Chapter 1: Discovery", "Chapter 2: Training", "Chapter 3: Revelation", "Chapter 4: Escape"]}\n```']
        if "[[ ## arc_outline ## ]]" in content or ('"arc_outline"' in content and "5-10 major events" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "arc_outline": ["Inciting incident", "First reversal", "Midpoint escalation", "Darkest turn", "Act climax"]}\n```']
        if "[[ ## world_bible ## ]]" in content or ('"world_bible"' in content and "setting, lore, and characters" in content):
            return ['```json\n{"world_bible": "Mock world bible"}\n```']
        if "[[ ## plot_timeline ## ]]" in content or ('"plot_timeline"' in content and "A plot timeline." in content):
            return ['```json\n{"reasoning": "Mock reasoning", "plot_timeline": "Mock timeline"}\n```']
        if "[[ ## locations ## ]]" in content or ('"locations"' in content and "Places and locations" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "locations": "Mock locations"}\n```']
        if "[[ ## characters ## ]]" in content or ('"characters"' in content and "Character descriptions" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "characters": "Mock characters"}\n```']
        if "[[ ## world_rules ## ]]" in content or ('"world_rules"' in content and "Rules of the world" in content):
            return ['```json\n{"reasoning": "Mock reasoning", "world_rules": "Mock rules"}\n```']
        if "[[ ## spine_template ## ]]" in content or ('"spine_template"' in content and "Once upon a time" in content):
            return ['```json\n{"spine_template": "Mock spine"}\n```']
        if "[[ ## core_premise ## ]]" in content or ('"core_premise"' in content and "summarizing the foundation" in content):
            return ['```json\n{"core_premise": "Mock premise"}\n```']

        if "character_visuals" in content and "reference_mix" in content:
            return ['```json\n{"character_visuals": [{"name": "Mock Hero", "reference_mix": "a mix of Guts from Berserk and Zuko from Avatar", "distinguishing_features": "short black hair, amber eyes, burn scar on left cheek, dark leather armor", "full_prompt": "anime portrait, a mix of Guts and Zuko, short black hair, amber eyes, burn scar, dark armor"}]}\n```']
        if "image_prompt" in content and "character_visuals_summary" in content:
            return ['```json\n{"image_prompt": "anime scene, a warrior standing in a dark cathedral, dramatic lighting"}\n```']

        # Fallback to general input presence checks but very carefully
        if "questions_with_answers" in content:
            return ['```json\n{"questions_with_answers": [{"question": "Mock?", "proposed_answer": "Yes"}]}\n```']
        elif "core_premise" in content and "spine_template" not in content:
            return ['```json\n{"core_premise": "Mock premise"}\n```']
        elif "spine_template" in content and "world_bible" not in content:
            return ['```json\n{"spine_template": "Mock spine"}\n```']
        elif "world_bible" in content and "arc_outline" not in content:
            return ['```json\n{"world_bible": "Mock world bible"}\n```']
        elif "arc_outline" in content and "chapter_plan" not in content:
            return ['```json\n{"reasoning": "Mock reasoning", "arc_outline": ["Inciting incident", "First reversal", "Midpoint escalation", "Darkest turn", "Act climax"]}\n```']
        elif "chapter_plan" in content and "enhancers_guide" not in content and "story" not in content:
            return ['```json\n{"reasoning": "Mock reasoning", "chapter_plan": ["Chapter 1: Discovery", "Chapter 2: Training", "Chapter 3: Revelation", "Chapter 4: Escape"]}\n```']
        elif "enhancers_guide" in content and "story" not in content and "chapter_text" not in content:
            return ['```json\n{"reasoning": "Mock reasoning", "enhancers_guide": "Mock enhancers guide"}\n```']
        elif "chapter_text" in content and "expanded_chapter_text" not in content:
            return ['```json\n{"reasoning": "Mock reasoning", "title": "Mock Title", "chapter_text": "Mock chapter text"}\n```']
        elif "expanded_chapter_text" in content:
            return ['```json\n{"reasoning": "Mock reasoning", "expanded_chapter_text": "Mock expanded chapter text with richer detail and slower pacing."}\n```']
        elif "story" in content:
            return ['```json\n{"story": "Mock final story"}\n```']
        return ["Mock response"]

logger = logging.getLogger(__name__)


def configure_logging(verbosity: int = 0, log_file: str | None = None):
    level_map = {0: logging.WARNING, 1: logging.INFO, 2: logging.DEBUG, 3: logging.DEBUG}
    level = level_map.get(verbosity, logging.DEBUG)
    log_format = "%(asctime)s.%(msecs)03d %(levelname)s [%(name)s] %(message)s"
    date_format = "%Y-%m-%d %H:%M:%S"
    coloredlogs.install(
        level=level,
        fmt=log_format,
        datefmt=date_format,
    )

    if log_file:
        log_dir = os.path.dirname(os.path.abspath(log_file))
        if log_dir:
            os.makedirs(log_dir, exist_ok=True)
        file_handler = logging.FileHandler(log_file, mode="a", encoding="utf-8")
        file_handler.setLevel(logging.DEBUG)
        file_handler.setFormatter(logging.Formatter(log_format, datefmt=date_format))
        logging.getLogger().addHandler(file_handler)

    logger.setLevel(level)
    _http_loggers = ("httpx", "httpcore", "urllib3", "requests", "langfuse")
    _llm_loggers = ("litellm", "dspy", "langfuse", "openai", "anthropic")

    if verbosity <= 1:
        for name in _http_loggers + _llm_loggers:
            logging.getLogger(name).setLevel(logging.WARNING)
    elif verbosity == 2:
        for name in _llm_loggers:
            logging.getLogger(name).setLevel(logging.DEBUG)
        for name in _http_loggers:
            logging.getLogger(name).setLevel(logging.WARNING)
    else:
        for name in _llm_loggers + _http_loggers:
            logging.getLogger(name).setLevel(logging.DEBUG)


def test_pipeline(
    model_name="mock",
    api_base="http://localhost:11434",
    api_key=None,
    output_dir=".tmp",
    max_tokens=1024,
    cache=True,
    memory_cache=True,
    cache_dir=None,
):
    from image_gen import ImageGenerator

    kwargs = {"max_tokens": max_tokens}
    if api_base:
        kwargs["api_base"] = api_base

    if api_key is not None:
        kwargs["api_key"] = api_key
    elif "openai" in model_name.lower():
        env_key = os.environ.get("OPENAI_API_KEY")
        if env_key:
            kwargs["api_key"] = env_key
    elif "ollama" in model_name.lower():
        pass

    logger.info(f"Testing pipeline with model: {model_name}...")
    logger.debug(
        "Pipeline config: api_base=%r max_tokens=%r api_key_set=%r cache=%r memory_cache=%r cache_dir=%r",
        api_base,
        max_tokens,
        bool(kwargs.get("api_key")),
        cache,
        memory_cache,
        cache_dir,
    )

    dspy.configure_cache(
        enable_disk_cache=cache,
        enable_memory_cache=memory_cache,
        disk_cache_dir=cache_dir,
    )

    if os.environ.get("LANGFUSE_PUBLIC_KEY"):
        try:
            from openinference.instrumentation.dspy import DSPyInstrumentor
            DSPyInstrumentor().instrument()
        except Exception as exc:
            logger.warning("Langfuse DSPy callback handler unavailable: %s", exc)

    # For testing in an environment where no actual LLM API is reachable, use the MockLM.
    # To run actual integration tests, you'd provide an active OPENAI_API_KEY or local Ollama running.
    # If the user requested the mock model, or if we want to ensure tests always pass in CI, use MockLM.
    if model_name == "mock" or model_name == "test_mock":
        lm = MockLM()
        dspy.configure(lm=lm)
    else:
        # We assume OPENAI_API_KEY is available in the run_in_bash_session, if not, we skip the actual test
        if "openai" in model_name.lower() and not kwargs.get("api_key"):
            logger.warning("OPENAI_API_KEY not found. Skipping full integration test to avoid errors.")
            return

        lm = dspy.LM(model_name, cache=cache, **kwargs)
        dspy.configure(lm=lm)

    idea = "An unnamed child is raised by the Church as the ultimate weapon against demons. As child grows he learns that the church itself is corrupt and breeds demons for controlled chaos. The church recieves funding for protection and as such decides who should recieve help. The child eventually becomes overpowered and turns back on the Church"

    # 1. Questions
    q_gen = QuestionGenerator()
    q_result = q_gen(idea=idea)
    logger.info(f"Generated {len(q_result.questions_with_answers)} questions.")
    logger.debug("Questions: %s", [q.question for q in q_result.questions_with_answers])

    # Fake answers
    qa_text = ""
    for q in q_result.questions_with_answers:
        qa_text += f"Q: {q.question}\nA: {q.proposed_answer}\n\n"

    # 2. Core Premise
    cp_gen = CorePremiseGenerator()
    cp_result = cp_gen(idea=idea, qa_pairs=qa_text)
    logger.info("Core Premise generated.")
    logger.debug("Core premise preview: %.300s", cp_result.core_premise)

    # 3. Spine Template
    st_gen = SpineTemplateGenerator()
    st_result = st_gen(core_premise=cp_result.core_premise)
    logger.info("Spine Template generated.")
    logger.debug("Spine template preview: %.300s", st_result.spine_template)

    # 4. World Bible
    wb_gen = WorldBibleGenerator()
    wb_result = wb_gen(core_premise=cp_result.core_premise, spine_template=st_result.spine_template)
    logger.info("World Bible generated.")
    logger.debug("World bible preview: %.300s", wb_result.world_bible)

    # 5. Character Visual Descriptions
    cv_describer = CharacterVisualDescriber()
    cv_result = cv_describer(world_bible=wb_result.world_bible)
    print(f"Generated visuals for {len(cv_result.character_visuals)} characters.")
    for cv in cv_result.character_visuals:
        print(f"  - {cv.name}: {cv.reference_mix}")

    character_visuals_summary = "\n".join(
        f"- {cv.name}: {cv.reference_mix}. {cv.distinguishing_features}"
        for cv in cv_result.character_visuals
    )

    # 6. Mock image generation (no real API calls)
    with patch.object(ImageGenerator, "__init__", lambda self, **kw: None):
        img_gen = ImageGenerator()
        img_gen.api_token = "mock_token"
        img_gen.output_dir = MagicMock()

        with patch.object(img_gen, "generate_character_portrait", return_value="images/mock_portrait.png"):
            for cv in cv_result.character_visuals:
                path = img_gen.generate_character_portrait(prompt=cv.full_prompt, character_name=cv.name)
                print(f"  Mock portrait for {cv.name}: {path}")

    # 7. Story — use real randomness so probabilistic detail behavior matches production.
    story_gen = StoryGenerator()
    story_result = story_gen(core_premise=cp_result.core_premise, spine_template=st_result.spine_template, world_bible=wb_result.world_bible)
    logger.info("Story generated.")
    logger.debug("Arc outline count=%d", len(story_result.arc_outline) if isinstance(story_result.arc_outline, list) else 0)
    logger.debug("Chapter plan preview: %.500s", story_result.chapter_plan)
    logger.debug("Story preview: %.500s", story_result.story)

    # 8. Scene image prompts
    scene_prompt_gen = SceneImagePromptGenerator()
    prompt_result = scene_prompt_gen(
        chapter_text="Mock chapter text for testing",
        character_visuals_summary=character_visuals_summary,
    )
    if prompt_result.image_prompt.strip().lower() in {"{image_prompt}", "image_prompt", "...content..."}:
        logger.warning("Scene image prompt appears to be a placeholder: %r", prompt_result.image_prompt)
    logger.info(f"Scene image prompt: {prompt_result.image_prompt[:80]}...")

    logger.info("Test passed successfully!")

    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "story_output.md")
    logger.info(f"Saving story output to {output_path}...")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Story Output\n\n")
        f.write("## Core Premise\n")
        f.write(f"{cp_result.core_premise}\n\n")
        f.write("## Spine Template\n")
        f.write(f"{st_result.spine_template}\n\n")
        f.write("## World Bible\n")
        f.write(f"{wb_result.world_bible}\n\n")

        if cv_result.character_visuals:
            f.write("## Character Visuals\n\n")
            for cv in cv_result.character_visuals:
                f.write(f"### {cv.name}\n")
                f.write(f"**Reference:** {cv.reference_mix}\n\n")
                f.write(f"**Features:** {cv.distinguishing_features}\n\n")

        f.write("## Arc Outline\n")
        f.write(f"{story_result.arc_outline}\n\n")
        f.write("## Chapter Plan\n")
        f.write(f"{story_result.chapter_plan}\n\n")
        f.write("## Enhancers Guide\n")
        f.write(f"{story_result.enhancers_guide}\n\n")
        f.write("## Final Story\n")
        f.write(f"{story_result.story}\n")


@pytest.mark.parametrize(
    "payload,expected",
    [
        ({"": "Who is the hero?", "proposed_answer": "Kai"}, {"question": "Who is the hero?", "proposed_answer": "Kai"}),
        ({"question": "Where?", "answer": "Mars"}, {"question": "Where?", "proposed_answer": "Mars"}),
        ({"query": "When?", "response": "At dawn"}, {"question": "When?", "proposed_answer": "At dawn"}),
    ],
)
def test_question_with_answer_key_normalization(payload, expected):
    result = QuestionWithAnswer.model_validate(payload)
    assert result.model_dump() == expected


@pytest.mark.parametrize(
    "raw_title,expected_clean",
    [
        ("Chapter 1: The Awakening", "The Awakening"),
        ("Chapter 12 - Descent", "Descent"),
        ("chapter 3: rising dawn", "rising dawn"),
        ("Chapter 1. First Light", "First Light"),
        ("The Awakening", "The Awakening"),           # no prefix – unchanged
        ("Chapter One: Narrative", "Chapter One: Narrative"),  # spelled-out number – unchanged
    ],
)
def test_chapter_title_prefix_stripping(raw_title, expected_clean):
    from story_modules import _chapter_prefix_re
    clean = _chapter_prefix_re.sub('', raw_title).strip()
    assert clean == expected_clean


@pytest.mark.parametrize(
    "raw_title,expected_clean",
    [
        ("**Chapter 6: The Engine's Breath**", "The Engine's Breath"),
        ("__Chapter 10 - The Weight of Justice__", "The Weight of Justice"),
        ("### Chapter 3: The Weaponization of Kael", "The Weaponization of Kael"),
        ("\"Chapter 8: The Fractured Self\"", "The Fractured Self"),
    ],
)
def test_clean_chapter_title_strips_markdown_and_prefixes(raw_title, expected_clean):
    from story_modules import _clean_chapter_title
    assert _clean_chapter_title(raw_title) == expected_clean


def test_normalize_plot_timeline_deduplicates_contiguous_act_headings():
    from world_bible_modules import _normalize_plot_timeline

    raw_timeline = "\n".join(
        [
            "Act 1 - Setup",
            "Act 1 - Setup",
            "- Hero receives the call.",
            "Act 2: Confrontation",
            "Act 2: Confrontation",
            "- Stakes escalate.",
        ]
    )

    normalized = _normalize_plot_timeline(raw_timeline)
    assert normalized == "\n".join(
        [
            "Act 1 - Setup",
            "- Hero receives the call.",
            "Act 2: Confrontation",
            "- Stakes escalate.",
        ]
    )


def test_normalize_plot_timeline_keeps_noncontiguous_repeated_act_headings():
    from world_bible_modules import _normalize_plot_timeline

    raw_timeline = "\n".join(
        [
            "Act 1 - Setup",
            "- First beat.",
            "Act 1 - Setup",
            "- Later callback beat.",
        ]
    )

    normalized = _normalize_plot_timeline(raw_timeline)
    assert normalized == raw_timeline


def test_question_with_answer_does_not_promote_unrelated_fields():
    with pytest.raises(Exception):
        QuestionWithAnswer.model_validate({"question": "Why?", "confidence": 0.92})


def test_character_visual_normalizes_description_only_shape():
    result = CharacterVisual.model_validate(
        {
            "name": "Kael",
            "description": "scarred child warrior in dark combat harness",
        }
    )

    assert result.reference_mix == "scarred child warrior in dark combat harness"
    assert result.distinguishing_features == "scarred child warrior in dark combat harness"
    assert result.full_prompt == (
        "anime portrait of Kael, scarred child warrior in dark combat harness"
    )


def test_initialize_text_generators_uses_loader_when_enabled():
    with patch("main.try_load_optimized_module", return_value=True) as mocked_loader:
        generators = initialize_text_generators(
            use_optimized=True,
            optimized_manifest=".tmp/dspy_optimized/text_pipeline_manifest.json",
        )

    expected_module_names = {
        "QuestionGenerator",
        "CorePremiseGenerator",
        "SpineTemplateGenerator",
        "WorldBibleQuestionGenerator",
        "WorldBibleGenerator",
        "StoryGenerator",
        "ChapterInpaintingGenerator",
    }
    assert set(generators.keys()) == expected_module_names
    assert mocked_loader.call_count == len(expected_module_names)


def test_initialize_text_generators_skips_loader_when_disabled():
    with patch("main.try_load_optimized_module") as mocked_loader:
        generators = initialize_text_generators(use_optimized=False)

    assert "StoryGenerator" in generators
    assert "ChapterInpaintingGenerator" in generators
    mocked_loader.assert_not_called()


def test_chapter_inpainting_generator_expands_detected_chapters():
    dspy.configure(lm=MockLM())
    inpainting = ChapterInpaintingGenerator()
    story = (
        "### Chapter 1: Arrival\n\nThe caravan reached the city gates at dusk.\n\n"
        "### Chapter 2: The Oath\n\nShe swore to protect the archive."
    )

    result = inpainting(
        story=story,
        world_bible="Mock world bible",
        chapter_plan="Chapter 1: Arrival\nChapter 2: The Oath",
        expansion_ratio=1.3,
    )

    assert result.total_chapters == 2
    assert result.expanded_chapters == 2
    assert "### Chapter 1: Arrival" in result.story
    assert "### Chapter 2: The Oath" in result.story
    assert "Mock expanded chapter text" in result.story


def test_chapter_inpainting_generator_rejects_invalid_ratio():
    dspy.configure(lm=MockLM())
    inpainting = ChapterInpaintingGenerator()

    with pytest.raises(ValueError, match="expansion_ratio must be > 1.0"):
        inpainting(
            story="### Chapter 1: Start\n\nShort text.",
            world_bible="Mock world bible",
            chapter_plan="Chapter 1: Start",
            expansion_ratio=1.0,
        )

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Test AI DSPy Story Writer")
    parser.add_argument("--model", type=str, default=os.environ.get("MODEL", "mock"), help="The language model to use (e.g., openai/gpt-4o-mini, ollama_chat/llama3). Defaults to MODEL env var or mock.")
    parser.add_argument("--llm-url", type=str, default=os.environ.get("LLM_URL", "http://localhost:11434"), help="The custom API base URL (e.g., http://localhost:11434 for Ollama). Defaults to LLM_URL env var or http://localhost:11434.")
    parser.add_argument("--api-key", type=str, default=os.environ.get("API_KEY"), help="The API key for the model. Defaults to API_KEY env var.")
    parser.add_argument("--output-dir", type=str, default=".tmp", help="Path to save output to")
    parser.add_argument("--max_tokens", type=int, default=1024, help="The number of tokens for an LLM to output")
    parser.add_argument("--cache", action=argparse.BooleanOptionalAction, default=True, help="Enable/disable DSPy disk cache.")
    parser.add_argument("--memory-cache", action=argparse.BooleanOptionalAction, default=True, help="Enable/disable DSPy in-memory cache.")
    parser.add_argument("--cache-dir", type=str, default=os.environ.get("DSPY_CACHE_DIR"), help="Override DSPy disk cache directory.")
    parser.add_argument(
        "--log-file",
        type=str,
        default=os.environ.get("LOG_FILE", ".tmp/test_debug.log"),
        help="Path to write detailed logs (default: LOG_FILE env var or .tmp/test_debug.log).",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help="Logging verbosity: -v INFO, -vv LLM debug, -vvv full firehose.",
    )

    args = parser.parse_args()

    configure_logging(verbosity=args.verbose, log_file=args.log_file)


    test_pipeline(
        model_name=args.model,
        api_base=args.llm_url,
        api_key=args.api_key,
        output_dir=args.output_dir,
        max_tokens=args.max_tokens,
        cache=args.cache,
        memory_cache=args.memory_cache,
        cache_dir=args.cache_dir,
    )
